sudo: false

language: cpp
compiler: g++-4.9

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

before_install:
  - wget http://downloads.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2 -O boost.tar.bz2
  - tar jxf boost.tar.bz2

script:
  - cmake -DBoost_INCLUDE_DIR=boost_1_58_0 -D CMAKE_C_COMPILER=gcc-4.9 -D CMAKE_CXX_COMPILER=g++-4.9 CMakeLists.txt
  - make
