sudo: false

language: cpp
compiler: g++-5.2

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5.2" CC="gcc-5.2"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5.2
    - g++-5.2
    - libboost-system-dev
    - libboost-filesystem-dev

script: make
