sudo: false

language: cpp
compiler: g++-5

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

before_install:
  - wget http://downloads.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2\?r\=\&ts\=1444518156\&use_mirror\=skylineservers -O boost.tar.bz2
  - tar jxf boost.tar.bz2
  - export BOOST="boost_1_58_0"

script: make
