sudo: false

language: cpp
compiler: g++-5.1

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5.1" CC="gcc-5.1"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5.1
    - g++-5.1
    - libboost-system-dev
    - libboost-filesystem-dev

script: make
